name: Variables Workflow

on:
  push:
    branches:
      - main

jobs:
  check-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Print ACCESS_ID
        env:
          ACCESS_ID: ${{ secrets.ACCESS_ID }}
        run: echo "Access ID is $ACCESS_ID"